### ISSUE TITLE
[RFE] version and release template schema like AS3

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-fast-core#11]
Like other pieces of the ATC, it would be nice to have a versioned schema available from a folder at or near the top level.

AS3 as an example.  This provides a really quick, easy and consistent way to get the latest schema to use for validation in other tools, like the vscode-f5-fast extension.  
https://github.com/F5Networks/f5-appsvcs-extension/blob/master/schema/latest/as3-schema.json

I know the schema doesn't really change much right now, but having it there and versioned would follow similar practices in the other ATC modules and make the experience more cohesive.

**Comment by mstokes-f5** [comment]
I agree that the schema for template files should be more accessible. However, I am not sure if their is much benefit to maintaining a history of schema files like AS3 does. I would prefer something more than "to be consistent" to add the extra release burden. Do you have a need for the versions (the schema is already versioned by f5-fast-core releases), or would making the current schema available in `schemas/template.json` be sufficient?

**Comment by DumpySquare** [comment]
I agree.  Just making the schema easier to get to should be good enough.  I was just thinking about what if schema changes did happen in the future, how would that get tracked?

Maybe that is something for a conversation at a later date, but wanted to present the idea of setting that up now so there is a way track changes and not have to revisit this again.  All up to you though.  :)

**Comment by mstokes-f5** [comment]
Is there a need to track schema changes separately from `f5-fast-core` itself? In other words, to see version X.Y of the schema, one could look at version X.Y of `f5-fast-core`.

**Comment by DumpySquare** [comment]
I don't think so.  I keep going back to the way AS3 is doing it.  That seems to be rather robust.  But I don't see any reason why you couldn't just use the version of the npm package like you are indicating.
