### ISSUE TITLE
[RFE] support json/yaml template inputs

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-fast-core#16]
it seems that the fast engine only accepts string templates.

It would be super convenient and take the authoring process to the next level if the template parameter also support json/yaml.

Keeping the source template text as native json/yaml allows for easy editing during the authoring process.

This format would open the possibility of associating appropriate schemas for the different templates.  With schemas, comes a greatly enhanced user experience.  This would also play into templatizing other F5 declarations and providing a single interface to write declarations

May need to specify the template type to more easily identify and apply the appropriate schemas

![image](https://user-images.githubusercontent.com/3260966/107150193-49080900-6922-11eb-96b7-4dfa4475046f.png)

**Comment by shyawnkarim** [comment]
Thanks for suggesting this enhancement. We are now tracking this with internal ID MYSTIQUE-327.

**Comment by mstokes-f5** [comment]
Are you requesting that we do transforms of the rendered template text to the desired output format? If you are authoring JSON templates (`contentType: application/json`) or YAML (`contentType: application/x-yaml`) then the template source text will already be in those languages.

**Comment by DumpySquare** [comment]
I am asking that template text, along with the current option  of string, also accept json/yaml as input so the template body/text can be authored in yaml/json.

Right now, even though it's structured like json, the fast template template param is a long string

So, this:
![image](https://user-images.githubusercontent.com/3260966/107415488-0d636f80-6ad9-11eb-8f35-280933073e41.png)


Turns to this when jsonified:
![image](https://user-images.githubusercontent.com/3260966/107415558-22d89980-6ad9-11eb-8b6e-5bf1623bdc7c.png)


But if we jsonify the template string first, the entire template can be consumed/authored like this:
![image](https://user-images.githubusercontent.com/3260966/107415790-59aeaf80-6ad9-11eb-8605-41db7f00e006.png)


This true nested json/yaml template parameters would allow for nested schemas and provide feedback for modifying template bodys within the fast template itself.

**Comment by shyawnkarim** [comment]
Closing.

The team reviewed this request and will not be implementing it.
