### ISSUE TITLE
[RFE] render rest endpoint

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-fast-core#17]
User would like to confirm template output without having to send to as3.

a POST to the /mgmt/shared/fast/templates/{setName}/{templateName} with the template parameters should produce the rendered template output, nothing else.

```json
{
  "url": "/mgmt/shared/fast/templates/{setName}/{templateName}",
  "method": "POST",
  "data": {
    "parameters": {
      "tenant_name": "fastTen1",
      "application_name": "app1_http",
      "virtual_port": 80,
      "virtual_address": "10.90.0.10",
      "server_port": 8080,
      "server_addresses": [
        "10.90.0.11",
        "10.90.0.12"
      ]
    }
  }
}
```

**Comment by shyawnkarim** [comment]
Thanks for suggesting this enhancement. We are now tracking it with internal ID MYSTIQUE-328.

**Comment by mstokes-f5** [comment]
Was this intended for f5-appsvcs-templates? f5-fast-core does not have a REST API.

**Comment by DumpySquare** [comment]
Your right.  this one should be on the ilx side.  you want me to move it?

**Comment by mstokes-f5** [comment]
I tried using GitHub's Transfer Issue feature, but I couldn't transfer this issue to the f5-appsvcs-templates repo. So, yes, could you please move the issue yourself? Thanks!

**Comment by DumpySquare** [comment]
done, moved to https://github.com/F5Networks/f5-appsvcs-templates/issues/39
