### ISSUE TITLE
unable to submit rendered template

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-fast-core#3]
Using the mst from #2 I'm unable to "submit" the rendered template (syntax checks out).
```
Failed to submit application:
Error: Failed to get data from /mgmt/shared/fast/applications: 400 Bad Request
{
  "code": 400,
  "message": "HTML Tag-like Content in the Request URL/Body"
}
    at https://192.168.1.201/iapps/f5-appsvcs-templates/bundle.js:77275:23
```

**Comment by mstokes-f5** [comment]
This appears to be an f5-appsvcs-templates issue, and not f5-fast-core. I see that this has already been filed as F5Networks/f5-appsvcs-templates/issues/7, so I am closing this issue.
