### ISSUE TITLE
support for individual file to package/zip and loosen directory structure

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-fast-core#4]
Need support to specify a single file to be validated and zipped.  Currently, the "packageTemplateSet" only accepts a directory.    This would be incredibly useful when developing individual templates and while initially getting familiar with the tool.

Furthermore, being able to specify multiple files to be packaged would also be helpful to allow users to have other types of files in the same directory and not be so limited by directory file structure.  Or skip files that don't pass validation.

This is on a windows 10 machine with vscode/powershell

```
PS C:\Users\starlord\f5-ts-testing> npx fast packageTemplateSet .\tempSet\hello.mst
cli.js packageTemplateSet <templateSetPath> [dst]

build a package for a given template set

Positionals:
  templateSetPath  path to the directory containing template sources                                          [required]
  dst              optional location for the built package (defaults to the current working directory)

Options:
  --help     Show help                                                                                         [boolean]
  --version  Show version number                                                                               [boolean]

Error: ENOTDIR invalid cwd C:\Users\starlord\f5-ts-testing\tempSet\hello.mst
    at Glob._readdirError (C:\Users\starlord\f5-ts-testing\node_modules\glob\glob.js:592:21)
    at C:\Users\starlord\f5-ts-testing\node_modules\glob\glob.js:553:12
    at FSReqCallback.oncomplete (fs.js:154:23) {
  path: 'C:\\Users\\starlord\\f5-ts-testing\\tempSet\\hello.mst',
  code: 'ENOTDIR'
}
PS C:\Users\starlord\f5-ts-testing>
```

**Comment by mstokes-f5** [comment]
I like the idea of letting `packageTemplateSet` take a path to either a file or to a directory. I believe the same could be done for `validate`, which would make `validateTemplateSet` redundant. To make things consistent, I think we'd then want to rename `packageTemplateSet` to just `package`.

One area where this gets tricky is with dependent files. The CLI tool would have to scan the file to determine dependencies (e.g., types defined in a json file, other templates referenced via allOf/oneOf/anyOf, etc.) and make sure they get packaged too.

**Comment by DumpySquare** [comment]
Some time has passed on this, and knowing more about the template set flow, this feature is less important.  I think some examples of how to use this would help.  close if you want to focus table this idea for now.

**Comment by shyawnkarim** [comment]
We are not tracking this enhancement internally with ID MYSTIQUE-324.

**Comment by walterk82** [comment]
Having this feature would be stellar.  For our organization, we write our own template framework for merging iRules into an AS3 declaration at build/deploy time.  If this feature existed within FAST then we would not need our homebrew any more as iRules would have a friendly development environment by being included in the resulting AS3 declaration.

Without this feature we could only have limited deployment with FAST as we use a lot of iRules and base64 encoding them within the template is not consumable for end-users.

**Comment by shyawnkarim** [comment]
Closing.

After a review of this request, we have decided to not implement this feature.
