### ISSUE TITLE
[RFE] support to upload validated and packaged templates

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-fast-core#5]
It would be nice to have the tool not only validate, and package the templates but upload them to an f5 or FAST service also.  This could really streamline the authoring process.

**Comment by mstokes-f5** [comment]
While I see the utility in this, I believe it is out of scope for this project. This project and the accompanying CLI are for the template engine and language, not for interacting with BIG-IP or the FAST service (f5-appsvcs-templates) running on the BIG-IP. There is currently some BIG-IP-specific code in this repo (the AS3Driver), but there are talks in progress for moving this code elsewhere.

Pinging @zinkem5 in case he has different thoughts on scope.

**Comment by zinkem5** [comment]
I think this is a better feature for the SDK that focuses on communication with BIG-IP: https://www.npmjs.com/package/f5-sdk-js

FAST-core is primarily focused on template rendering and generic HTTP capabilities. BIG-IP specific code is out of scope for FAST-Core.

**Comment by DumpySquare** [comment]
Thanks for the feedback gents!  As recommended, I implemented this in the extension.
