### ISSUE TITLE
[RFE] add jsdoc documentation

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-fast-core#6]
To aid with integration with other tools and programs, it would be nice to have jsdoc information on functions to better understand usage, inputs, and outputs.

It can also help document all of the features and functions:

https://jsdoc.app/
https://jsdoc.app/about-getting-started.html

**Comment by mstokes-f5** [comment]
I agree that API docs are useful, important, and necessary. Any particular reason to use JSDoc (e.g., some sort of tool compatibility), or would any doc generator be sufficient?

**Comment by DumpySquare** [comment]
Being new to JS/TS my experience has been limited, but i have been using jsdocs with this extension and it integrates very nicely with vscode to show me function use/input/outputs while coding:

https://marketplace.visualstudio.com/items?itemName=DumpySquare.vscode-f5-fast

The f5-sdk-js seems to be doing it also:  https://github.com/f5devcentral/f5-sdk-js

Below is an example from vscode.  On the left you can see the function being called.  When you hover the mouse over it, it will tell you the jsdoc details.  The right side of the screen is the actually function definition that provides that pop-up.  In my practice it's been pretty easy to add this header to functions during testing.  It seems the added benefit is there are tools that can take all the jsdoc stuff and auto generate web documentation of all the functions and other things.  

![image](https://user-images.githubusercontent.com/3260966/84313920-d9404500-ab2c-11ea-95fa-68d43ae73ca3.png)

So, to loop back to your original question, I'm not stuck on jsdocs.  They just seem to be what I've picked up and my first suggestion in the absence of API docs.  I see it all over the vscode stuff and it's working nicely to provide documentation within the code and external.  :)

**Comment by shyawnkarim** [comment]
This enhancement to our documentation was included with [Release 0.7.0](https://github.com/f5devcentral/f5-fast-core/releases/tag/v0.7.0).
