### ISSUE TITLE
[RFE] Add an easy way to implement delimiter for rendered lists

### ISSUE THREAD

**Issue by BenEkpy** [f5devcentral/f5-fast-core#9]
When using mustache sections to parse a list, there no easy way to set a delimiter to render a correct JSON list.

For exemple, I want to create a list of service (IP+PORT) using an array where IP and PORT is defined for each service.

Using this template :
~~~
definitions:
  service:
    type: array
    items:
      - name: ip
      - name: port
  service_ref:
    template: |
      {{# service}}
        "{{ip}}:{{port}}"
      {{/ service}}

template: |
  {
    "service": [
       {{> service_ref}}
    ]
  }
~~~

... and this input :
~~~
{
    "service": [
        { "ip": "1.1.1.1", "port": "80" },
        { "ip": "1.1.1.2", "port": "80" }
     ]
}
~~~~

... Fast rendered an invalid JSON Payload
~~~
{
  "service": [
       "1.1.1.1:80"
       "1.1.1.2:80"
  ]
}
~~~

## Desired Solution

An automatic section called "last" could be used to set delimiter except for the last item of the  list : {{^last}} , {{/last}}

#### template.yml

~~~
definitions:
  service:
    type: array
    items:
      - name: ip
      - name: port
  service_ref:
    template: |
      {{# service}}
        "{{ip}}:{{port}}"
        {{^last}} , {{/last}}
      {{/ service}}

template: |
  {
    "service": [
       {{> service_ref}}
    ]
  }
~~~

#### input file
~~~
{
    "service": [
        { "ip": "1.1.1.1", "port": "80" },
        { "ip": "1.1.1.2", "port": "80" }
     ]
}
~~~~

#### output rendered by fast
~~~
{
  "service": [
       "1.1.1.1:80",
       "1.1.1.2:80"
  ]
}
~~~

## Alternative found

Set an "last" key on the last item of the list. This solution isn't really clean ...

#### input file
~~~
{
    "service": [
        { "ip": "1.1.1.1", "port": "80" },
        { "ip": "1.1.1.2", "port": "80", "last": true }
     ]
}
~~~~

#### output rendered by fast
~~~
{
  "service": [
       "1.1.1.1:80",
       "1.1.1.2:80"
  ]
}
~~~

**Comment by shyawnkarim** [comment]
Thanks for suggesting this enhancement. We are now tracking this internally with ID MYSTIQUE-325.

**Comment by shyawnkarim** [comment]
Closing.

Our team discussed your request and we have decided not to implement it. FAST will automatically strip dangling commas from template outputs that have a contentType of application/json, so we are not moving forward with any workarounds to control rendering of the last item in a list.

Please feel free to reopen if there is any additional information you would like to provide around this.

**Comment by DumpySquare** [comment]
Is there an example to show how to accomplish the ask here?

**Comment by BenEkpy** [comment]
+1
